#!/bin/bash

function run
{
    case $1 in
        'solve')
            solve $2
            ;;
        'test')
            test $2
            ;;
        *)
            echo "Invalid argument:" $1
            ;;
    esac
}

function solve
{
    case $1 in
        'silver')
            echo $(solve_silver puzzle.txt)
            ;;
        'gold')
            echo $(solve_gold puzzle.txt)
            ;;
        *)
            echo "Invalid argument:" $1
            exit 1
            ;;
    esac
}

function test
{
    case $1 in
        'silver')
            actual=$(solve_silver "$silver_test_file")
            expected=$silver_expected_test_result
            ;;
        'gold')
            actual=$(solve_gold "$gold_test_file")
            expected=$gold_expected_test_result
            ;;
        *)
            echo "Invalid argument:" $1
            exit 1
            ;;
    esac

    print_test_result $actual $expected
}

function print_test_result
{
    GREEN=$(tput setaf 2)
    RED=$(tput setaf 1)
    RESET=$(tput sgr0)

    actual=$1
    expected=$2

    if [[ $actual == $expected ]]
    then
        printf "$GREEN\xE2\x9C\x94$RESET $actual\n"
    else
        printf "$RED\xE2\x9D\x8C$RESET actual: $actual, expected: $expected\n"
    fi
}
