#!/bin/bash

source ../lib.sh

function solve_silver
{
	./sum.awk "$1"
}

function solve_gold
{
	./replace.awk "$1" | ./sum.awk;
}

silver_test_file="silver-test.txt"
gold_test_file="gold-test.txt"

silver_expected_test_result=142
gold_expected_test_result=281

run $1 $2
