#!/bin/bash

source ../lib

function filter
{
    tr -cd '0-9\n'
}

function solve_silver
{
    cat $1 | filter | ./sum.awk
}

function solve_gold
{
    ./replace.sed "$1" | filter | ./sum.awk;
}

silver_test_file="silver-test.txt"
gold_test_file="gold-test.txt"

silver_expected_test_result=142
gold_expected_test_result=281

run $1 $2
