#!/bin/bash

source ../lib.sh

function solve_silver
{
	./sum_points.awk "$1"
}

function solve_gold
{
	./sum_cards.awk "$1"
}

silver_test_file="test.txt"
gold_test_file="test.txt"

silver_expected_test_result=13
gold_expected_test_result=30

run $1 $2
